### ISSUE TITLE
complete the build for the last commit

### ISSUE THREAD

**Issue by cyberkhalil** [circleci/cci-demo-android#1]
Hello , when i saw the app from github page online the circle ci tells that it fails in testing but after i clicked on it i think u just cancelled the last test so complete the building for it to see that's demo testing is running properly.

That's how it's looks like now
![image](https://user-images.githubusercontent.com/26520106/42188494-ca24b8c0-7e5c-11e8-953a-aa5ea3aa53d4.png)

That's the building dashboard for the project
![image](https://user-images.githubusercontent.com/26520106/42188520-dc8db44e-7e5c-11e8-85ee-6219ef588c39.png)

**Comment by drazisil** [comment]
Hello,

This is an old project that no longer works on CircleCI 2.0 in it's current configuration

The latest and most current documentation on build Android on CircleCI 2.0 is here https://circleci.com/docs/2.0/language-android/
